Aq 34 eslint prettier
AzenoIT/azeno pull request #3
Opened 2023-03-07 17:32 UTC by ToJestKrzysio

# Description
Added eslint and prettier, with configuration to run it automatically via Vite.

[Fixes](https://azeno.youtrack.cloud/issue/AQ-34/Configure-ESLint-Prettier)

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-03-07 18:28 UTC, olivergav commented on quiz/web/.prettierrc.json
> +	"printWidth": 120,
<img width="770" alt="image" src="https://user-images.githubusercontent.com/90700152/223516213-231e1590-1c73-4c0a-bd48-2697349f58c7.png">

Prettier nie zaleca użycia więcej niż 80 znaków.
https://prettier.io/docs/en/options.html#print-width

2023-03-07 18:35 UTC, pawelkonior requested changes
Coś jest nie tak z wcięcami, są na 8 znaków, praktycznie nie da się tego kodu czytać.

2023-03-07 18:35 UTC, pawelkonior commented on quiz/web/.prettierrc.json
> +	"printWidth": 120,
w dobie panoramicznych ekranów, 120 znaków jest spoko :)

2023-03-07 19:50 UTC, ToJestKrzysio commented on quiz/web/.prettierrc.json
> +	"singleAttributePerLine": false,
Jeszcze do tej pory nie widziałem żeby coś takiego się stało na tych ustawieniach :D

2023-03-07 20:22 UTC, olivergav approved these changes

2023-03-08 08:36 UTC, pawelkonior approved these changes
Good job!

2023-03-08 13:12 UTC, merged