Aq 74 create player view
AzenoIT/azeno pull request #32
Opened 2023-03-29 22:31 UTC by MWasile

# Description

added view and serializer for player model, which enable creating new players with a nickname
## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

6 unit tests 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The related memme has been added

![img](https://wykop.pl/cdn/c3201142/77400bac5f71b01d52c8fc85fdc5e995aedbd742527a08bd6385c6c2e3252757.jpg?author=Hekate_1988&auth=1f7fb864e7741a70a540fb7bdacd38e9)

2023-03-30 08:23 UTC, martynawitkowska requested changes

2023-03-30 08:36 UTC, SlawCzech commented
Everything works fine for me. Create-player works, tests pass. One side-comment though - in models I would change 'is_bot' field 'verbose name' to "Bot player", because showing only "Player type" in admin is very unclear.

2023-03-30 08:37 UTC, SlawCzech approved these changes
Works fine for me.

2023-03-30 18:40 UTC, ToJestKrzysio commented on quiz/proxy/default.conf
> +    location /api/v1/ {
seems fine for now

2023-03-31 21:04 UTC, martynawitkowska approved these changes
Approving, but remove unused imports :D

2023-03-31 21:04 UTC, martynawitkowska commented on quiz/backend/players/tests/test_serializers.py
> +from datetime import datetime
unused import

2023-03-31 21:04 UTC, martynawitkowska commented on quiz/backend/players/tests/test_views.py
> +import json
unused import

2023-03-31 23:04 UTC, merged

2023-04-01 08:02 UTC, ToJestKrzysio reviewed
Just notes

2023-04-01 08:02 UTC, ToJestKrzysio commented on quiz/backend/players/tests/test_views.py
> +    assert response.data["nick"] == "test_nick"
"test_nick" could be generated by fixture and used by test and fixture generating data.